packages:
  left_bed_sensor: !include
    file: sensors.yaml
    vars:
      sensor_name: Left
      sensor_id: left
      sensor_gpio: GPIO4

  right_bed_sensor: !include
    file: sensors.yaml
    vars:
      sensor_name: Right
      sensor_id: right
      sensor_gpio: GPIO2

sensor:
- platform: uptime
  type: seconds
  id: bed_presence_uptime
  name: "Uptime"
- platform: wifi_signal
  name: "WiFi Signal"
  id: wifi_signal_dBm
  update_interval: 30s
- platform: copy # Reports the WiFi signal strength in %
  source_id: wifi_signal_dBm
  name: "WiFi Signal Percent"
  filters:
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
  unit_of_measurement: "%"
  entity_category: "diagnostic"
  device_class: ""
  
globals:
- id: low_value
  type: float
  restore_value: yes
  initial_value: '${initial_low_value}'
- id: high_value
  type: float
  restore_value: yes
  initial_value: '${initial_high_value}'
substitutions:
  initial_low_value: "11000"
  initial_high_value: "70000"
binary_sensor:
- platform: template
  name: Bed Occupied Both (Fast)
  id: bed_occupied_both_fast
  device_class: occupancy
  icon: mdi:bunk-bed
  disabled_by_default: true
  lambda: return id(bed_occupied_left_fast).state && id(bed_occupied_right_fast).state;

- platform: template
  name: Bed Occupied Either (Fast)
  id: bed_occupied_either_fast
  device_class: occupancy
  icon: mdi:bunk-bed
  disabled_by_default: true
  lambda: return id(bed_occupied_left_fast).state || id(bed_occupied_right_fast).state;

- platform: template
  name: Bed Occupied Both
  id: bed_occupied_both
  device_class: occupancy
  icon: mdi:bunk-bed
  lambda: return id(bed_occupied_left).state && id(bed_occupied_right).state;

- platform: template
  name: Bed Occupied Either
  id: bed_occupied_either
  device_class: occupancy
  icon: mdi:bunk-bed
  lambda: return id(bed_occupied_left).state || id(bed_occupied_right).state;




button:
- platform: restart
  name: Restart
  id: btn_restart
  entity_category: "diagnostic"
